export enum ServiceCategory {
    OIL_CHANGE = 'OIL_CHANGE',
    BRAKE_SERVICE = 'BRAKE_SERVICE',
    TRANSMISSION_SERVICE = 'TRANSMISSION_SERVICE',
    TIRE_SERVICE = 'TIRE_SERVICE',
    FLUID_SERVICE = 'FLUID_SERVICE',
    ENGINE_SERVICE = 'ENGINE_SERVICE',
    INSPECTION = 'INSPECTION',
    BATTERY_SERVICE = 'BATTERY_SERVICE',
    FILTER_SERVICE = 'FILTER_SERVICE',
    LIGHT_SERVICE = 'LIGHT_SERVICE',
    OTHER = 'OTHER',
}