export enum ServiceCategory {
    OIL_CHANGE = 'OIL_CHANGE',
    BRAKE_SERVICE = 'BRAKE_SERVICE',
    TRANSMISSION_SERVICE = 'TRANSMISSION_SERVICE',
    TIRE_SERVICE = 'TIRE_SERVICE',
    OTHER = 'OTHER',
}