-- Generated from European-Car-Database-by-Teoalida-make-model.xlsx
-- Source sheet: Make-Model
-- Source note: Updated 22 April 2025
-- Generated rows: 1636
-- Target dialect: PostgreSQL

DROP TABLE IF EXISTS european_car_make_models;

CREATE TABLE european_car_make_models (
    id BIGSERIAL PRIMARY KEY,
    brand TEXT NOT NULL,
    model TEXT NOT NULL,
    source_updated DATE DEFAULT DATE '2025-04-22',
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX idx_european_car_make_models_brand ON european_car_make_models (brand);
CREATE INDEX idx_european_car_make_models_brand_model ON european_car_make_models (brand, model);

INSERT INTO european_car_make_models (brand, model) VALUES
    ('Abarth', 'Punto'),
    ('Abarth', '124 Spider'),
    ('Abarth', '500/595/695'),
    ('Abarth', '600'),
    ('Aiways', 'U5'),
    ('Aiways', 'U6'),
    ('Aixam', 'Ambition'),
    ('Aixam', 'Emotion'),
    ('Aixam', 'Mega'),
    ('Aixam', 'Minauto'),
    ('Aixam', 'Sensation'),
    ('Alfa Romeo', 'Alfasud'),
    ('Alfa Romeo', 'Alfasud Sprint'),
    ('Alfa Romeo', 'Alfetta'),
    ('Alfa Romeo', 'Alfetta GTV'),
    ('Alfa Romeo', 'Arna'),
    ('Alfa Romeo', 'Brera'),
    ('Alfa Romeo', 'Giulia'),
    ('Alfa Romeo', 'Giulia GT'),
    ('Alfa Romeo', 'Giulia Spider'),
    ('Alfa Romeo', 'Giulietta'),
    ('Alfa Romeo', 'GT'),
    ('Alfa Romeo', 'GTV'),
    ('Alfa Romeo', 'Junior'),
    ('Alfa Romeo', 'MiTo'),
    ('Alfa Romeo', 'Montreal'),
    ('Alfa Romeo', 'Spider'),
    ('Alfa Romeo', 'Sprint'),
    ('Alfa Romeo', 'Stelvio'),
    ('Alfa Romeo', 'SZ/RZ Zagato'),
    ('Alfa Romeo', 'Tonale'),
    ('Alfa Romeo', '4C'),
    ('Alfa Romeo', '6'),
    ('Alfa Romeo', '8C'),
    ('Alfa Romeo', '33'),
    ('Alfa Romeo', '33'),
    ('Alfa Romeo', '75'),
    ('Alfa Romeo', '90'),
    ('Alfa Romeo', '145'),
    ('Alfa Romeo', '146'),
    ('Alfa Romeo', '147'),
    ('Alfa Romeo', '155'),
    ('Alfa Romeo', '156'),
    ('Alfa Romeo', '159'),
    ('Alfa Romeo', '164'),
    ('Alfa Romeo', '166'),
    ('Alfa Romeo', '1750/2000 Berlina'),
    ('Alfa Romeo', '2000'),
    ('Alfa Romeo', '2600'),
    ('ALPINA', 'B3/B6/B8/C1/D3 (3er-Reihe)'),
    ('ALPINA', 'B4/D4 (4er-Reihe)'),
    ('ALPINA', 'B5/B7/B9/B10/D5/D10 (5er-Reihe)'),
    ('ALPINA', 'B6 (6er-Reihe)'),
    ('ALPINA', 'B7/B11/B12 (7er-Reihe)'),
    ('ALPINA', 'B8/B12 (8er-Reihe)'),
    ('ALPINA', 'Roadster (Z1)'),
    ('ALPINA', 'Roadster (Z8)'),
    ('ALPINA', 'Roadster S (Z4)'),
    ('ALPINA', 'XB7'),
    ('ALPINA', 'XD3'),
    ('ALPINA', 'XD4'),
    ('Alpine', 'A110'),
    ('Alpine', 'A290'),
    ('Alpine', 'A390'),
    ('Alpine', 'A610'),
    ('Alpine', 'Renault Alpine A310'),
    ('Alpine', 'Renault Alpine A310 V6'),
    ('Alpine', 'Renault Alpine V6 GT/Turbo'),
    ('Amphicar', '770'),
    ('ARI Motors', 'Bruni'),
    ('ARI Motors', 'Poly'),
    ('ARI Motors', 'Soleno'),
    ('ARI Motors', '452/802'),
    ('ARI Motors', '901'),
    ('ARI Motors', '901 XL'),
    ('ARI Motors', '902'),
    ('ARI Motors', '1710'),
    ('Aston Martin', 'Cygnet'),
    ('Aston Martin', 'DB AR1'),
    ('Aston Martin', 'DB11'),
    ('Aston Martin', 'DB12'),
    ('Aston Martin', 'DB4'),
    ('Aston Martin', 'DB4 GT Zagato'),
    ('Aston Martin', 'DB5'),
    ('Aston Martin', 'DB6'),
    ('Aston Martin', 'DB7'),
    ('Aston Martin', 'DB7 Zagato'),
    ('Aston Martin', 'DB9'),
    ('Aston Martin', 'DBS'),
    ('Aston Martin', 'DBX'),
    ('Aston Martin', 'Lagonda'),
    ('Aston Martin', 'Lagonda Rapide'),
    ('Aston Martin', 'Lagonda Taraf'),
    ('Aston Martin', 'One-77'),
    ('Aston Martin', 'Rapide'),
    ('Aston Martin', 'V12 Zagato'),
    ('Aston Martin', 'V8'),
    ('Aston Martin', 'V8 Zagato'),
    ('Aston Martin', 'Valhalla'),
    ('Aston Martin', 'Valiant'),
    ('Aston Martin', 'Valour'),
    ('Aston Martin', 'Vanquish'),
    ('Aston Martin', 'Vanquish Zagato'),
    ('Aston Martin', 'Vantage'),
    ('Aston Martin', 'Virage'),
    ('Audi', 'A1'),
    ('Audi', 'A2'),
    ('Audi', 'A3'),
    ('Audi', 'A4'),
    ('Audi', 'A5'),
    ('Audi', 'A6'),
    ('Audi', 'A7'),
    ('Audi', 'A8'),
    ('Audi', 'allroad quattro'),
    ('Audi', 'Cabriolet'),
    ('Audi', 'CoupÃ©'),
    ('Audi', 'e-tron'),
    ('Audi', 'e-tron GT'),
    ('Audi', 'F103'),
    ('Audi', 'Q2'),
    ('Audi', 'Q3'),
    ('Audi', 'Q4 e-tron'),
    ('Audi', 'Q5'),
    ('Audi', 'Q6 e-tron'),
    ('Audi', 'Q7'),
    ('Audi', 'Q8'),
    ('Audi', 'Q8 e-tron'),
    ('Audi', 'quattro'),
    ('Audi', 'R8'),
    ('Audi', 'Sport quattro'),
    ('Audi', 'TT'),
    ('Audi', 'V8'),
    ('Audi', '50'),
    ('Audi', '80'),
    ('Audi', '90'),
    ('Audi', '100'),
    ('Audi', '200'),
    ('Auto Union', '1000'),
    ('Auto Union', '1000 Sp'),
    ('Autobianchi', 'A111'),
    ('Autobianchi', 'A112'),
    ('Autobianchi', 'Primula'),
    ('BAIC', 'Beijing X35'),
    ('BAIC', 'Beijing X55'),
    ('BAIC', 'Beijing X75'),
    ('BAIC', 'BJ30'),
    ('BAIC', 'BJ40'),
    ('BAIC', 'BJ60'),
    ('BAW', '212'),
    ('Bentley', 'Arnage'),
    ('Bentley', 'Azure'),
    ('Bentley', 'Bentayga'),
    ('Bentley', 'Brooklands'),
    ('Bentley', 'Brooklands R'),
    ('Bentley', 'Continental'),
    ('Bentley', 'Flying Spur'),
    ('Bentley', 'Mulsanne'),
    ('Bentley', 'Turbo RT'),
    ('Bestune', 'B70'),
    ('Bestune', 'T77 Pro'),
    ('Bitter', 'Diplomat CD'),
    ('Bitter', 'SC'),
    ('BMW', 'E3'),
    ('BMW', 'E9'),
    ('BMW', 'Glas 1600 GT'),
    ('BMW', 'Glas 3000 V8'),
    ('BMW', 'i3'),
    ('BMW', 'i4'),
    ('BMW', 'i5'),
    ('BMW', 'i7'),
    ('BMW', 'i8'),
    ('BMW', 'Isetta'),
    ('BMW', 'iX'),
    ('BMW', 'iX1'),
    ('BMW', 'iX2'),
    ('BMW', 'iX3'),
    ('BMW', 'M1'),
    ('BMW', 'Neue Klasse'),
    ('BMW', 'X1'),
    ('BMW', 'X2'),
    ('BMW', 'X3'),
    ('BMW', 'X4'),
    ('BMW', 'X5'),
    ('BMW', 'X6'),
    ('BMW', 'X7'),
    ('BMW', 'XM'),
    ('BMW', 'Z1'),
    ('BMW', 'Z3'),
    ('BMW', 'Z4'),
    ('BMW', 'Z8'),
    ('BMW', '1er-Reihe'),
    ('BMW', '02er-Reihe'),
    ('BMW', '2er-Reihe'),
    ('BMW', '2er-Reihe Active/Gran Tourer'),
    ('BMW', '2er-Reihe Gran CoupÃ©'),
    ('BMW', '3er-Reihe'),
    ('BMW', '4er-Reihe'),
    ('BMW', '5er-Reihe'),
    ('BMW', '6er-Reihe'),
    ('BMW', '6er-Reihe GT'),
    ('BMW', '7er-Reihe'),
    ('BMW', '8er-Reihe'),
    ('BMW', '501/502'),
    ('BMW', '503'),
    ('BMW', '507'),
    ('BMW', '600'),
    ('BMW', '700/LS'),
    ('BMW', '3200 CS'),
    ('Borgward', 'Arabella'),
    ('Borgward', 'BX7'),
    ('Borgward', 'Hansa 1500/1800'),
    ('Borgward', 'Hansa 2400'),
    ('Borgward', 'Isabella'),
    ('Borgward', 'P 100'),
    ('Bovensiepen', 'Zagato'),
    ('Brilliance', 'BS4'),
    ('Brilliance', 'BS6'),
    ('Bugatti', 'Chiron'),
    ('Bugatti', 'Divo'),
    ('Bugatti', 'EB 110'),
    ('Bugatti', 'Veyron'),
    ('BYD', 'Atto 2'),
    ('BYD', 'Atto 3'),
    ('BYD', 'Dolphin'),
    ('BYD', 'Dolphin Surf'),
    ('BYD', 'ETP3'),
    ('BYD', 'Han'),
    ('BYD', 'Seal'),
    ('BYD', 'Seal 6'),
    ('BYD', 'Seal U'),
    ('BYD', 'Sealion 7'),
    ('BYD', 'Tang'),
    ('Cadillac', 'ATS'),
    ('Cadillac', 'BLS'),
    ('Cadillac', 'CT6'),
    ('Cadillac', 'CTS'),
    ('Cadillac', 'Escalade'),
    ('Cadillac', 'LYRIQ'),
    ('Cadillac', 'OPTIQ'),
    ('Cadillac', 'Seville'),
    ('Cadillac', 'SRX'),
    ('Cadillac', 'STS'),
    ('Cadillac', 'VISTIQ'),
    ('Cadillac', 'XLR'),
    ('Cadillac', 'XT4'),
    ('Cadillac', 'XT5'),
    ('Casalini', 'M20'),
    ('Casalini', '550'),
    ('Changan Deepal', 'S05'),
    ('Changan Deepal', 'S07'),
    ('Chevrolet', 'Alero'),
    ('Chevrolet', 'Astro'),
    ('Chevrolet', 'Aveo'),
    ('Chevrolet', 'Blazer'),
    ('Chevrolet', 'Camaro'),
    ('Chevrolet', 'Captiva'),
    ('Chevrolet', 'Corvette'),
    ('Chevrolet', 'Cruze'),
    ('Chevrolet', 'Epica'),
    ('Chevrolet', 'Evanda'),
    ('Chevrolet', 'HHR'),
    ('Chevrolet', 'Kalos'),
    ('Chevrolet', 'Lacetti'),
    ('Chevrolet', 'Malibu'),
    ('Chevrolet', 'Matiz'),
    ('Chevrolet', 'Nubira'),
    ('Chevrolet', 'Orlando'),
    ('Chevrolet', 'Rezzo'),
    ('Chevrolet', 'S10 Pickup'),
    ('Chevrolet', 'Spark'),
    ('Chevrolet', 'Suburban'),
    ('Chevrolet', 'Tahoe'),
    ('Chevrolet', 'Trailblazer'),
    ('Chevrolet', 'Trans Sport'),
    ('Chevrolet', 'Trax'),
    ('Chevrolet', 'Volt'),
    ('Chrysler', 'Crossfire'),
    ('Chrysler', 'Grand Voyager'),
    ('Chrysler', 'Neon'),
    ('Chrysler', 'New Yorker'),
    ('Chrysler', 'PT Cruiser'),
    ('Chrysler', 'Sebring'),
    ('Chrysler', 'Stratus'),
    ('Chrysler', 'Viper'),
    ('Chrysler', 'Vision'),
    ('Chrysler', 'Voyager'),
    ('Chrysler', '300C'),
    ('Chrysler', '300M'),
    ('Citroen', 'Ami'),
    ('Citroen', 'Ami 6'),
    ('Citroen', 'Ami 8/Super'),
    ('Citroen', 'AX'),
    ('Citroen', 'Berlingo'),
    ('Citroen', 'BX'),
    ('Citroen', 'C-Crosser'),
    ('Citroen', 'C-Elysee'),
    ('Citroen', 'C-Zero'),
    ('Citroen', 'C1'),
    ('Citroen', 'C2'),
    ('Citroen', 'C3'),
    ('Citroen', 'C3 Aircross'),
    ('Citroen', 'C3 Picasso'),
    ('Citroen', 'C3 Pluriel'),
    ('Citroen', 'C4'),
    ('Citroen', 'C4 Aircross'),
    ('Citroen', 'C4 Cactus'),
    ('Citroen', 'C4 Picasso'),
    ('Citroen', 'C4 Spacetourer'),
    ('Citroen', 'C5'),
    ('Citroen', 'C5 Aircross'),
    ('Citroen', 'C5 X'),
    ('Citroen', 'C6'),
    ('Citroen', 'C8'),
    ('Citroen', 'CX'),
    ('Citroen', 'DS'),
    ('Citroen', 'DS 3'),
    ('Citroen', 'DS 4'),
    ('Citroen', 'DS 5'),
    ('Citroen', 'Dyane'),
    ('Citroen', 'E-Mehari'),
    ('Citroen', 'Evasion'),
    ('Citroen', 'GS/GSA'),
    ('Citroen', 'Holidays'),
    ('Citroen', 'Jumper'),
    ('Citroen', 'Jumpy'),
    ('Citroen', 'LN'),
    ('Citroen', 'Nemo'),
    ('Citroen', 'Saxo'),
    ('Citroen', 'SM'),
    ('Citroen', 'Spacetourer'),
    ('Citroen', 'Visa'),
    ('Citroen', 'Xantia'),
    ('Citroen', 'XM'),
    ('Citroen', 'Xsara'),
    ('Citroen', 'Xsara Picasso'),
    ('Citroen', 'ZX'),
    ('Citroen', '2CV'),
    ('CUPRA', 'Ateca'),
    ('CUPRA', 'Born'),
    ('CUPRA', 'Formentor'),
    ('CUPRA', 'Leon'),
    ('CUPRA', 'Raval'),
    ('CUPRA', 'Tavascan'),
    ('CUPRA', 'Terramar'),
    ('Dacia', 'Bigster'),
    ('Dacia', 'Dokker'),
    ('Dacia', 'Duster'),
    ('Dacia', 'Jogger'),
    ('Dacia', 'Lodgy'),
    ('Dacia', 'Logan'),
    ('Dacia', 'Sandero'),
    ('Dacia', 'Spring'),
    ('Daewoo', 'Espero'),
    ('Daewoo', 'Evanda'),
    ('Daewoo', 'Kalos'),
    ('Daewoo', 'Korando'),
    ('Daewoo', 'Lacetti'),
    ('Daewoo', 'Lanos'),
    ('Daewoo', 'Leganza'),
    ('Daewoo', 'Matiz'),
    ('Daewoo', 'Musso'),
    ('Daewoo', 'Nexia'),
    ('Daewoo', 'Nubira'),
    ('Daewoo', 'Rezzo'),
    ('DAF', '30/31/32 Daffodil'),
    ('DAF', '33'),
    ('DAF', '44'),
    ('DAF', '55'),
    ('DAF', '66'),
    ('DAF', '600'),
    ('DAF', '750'),
    ('Daihatsu', 'Applause'),
    ('Daihatsu', 'Charade'),
    ('Daihatsu', 'Copen'),
    ('Daihatsu', 'Cuore'),
    ('Daihatsu', 'Feroza'),
    ('Daihatsu', 'Gran Move'),
    ('Daihatsu', 'Hijet'),
    ('Daihatsu', 'Materia'),
    ('Daihatsu', 'Move'),
    ('Daihatsu', 'Rocky'),
    ('Daihatsu', 'Sirion'),
    ('Daihatsu', 'Terios'),
    ('Daihatsu', 'Trevis'),
    ('Daihatsu', 'YRV'),
    ('Datsun', 'Bluebird'),
    ('Datsun', 'Cherry'),
    ('Datsun', 'Laurel'),
    ('Datsun', 'Skyline'),
    ('Datsun', 'Sunny'),
    ('Datsun', 'Violet'),
    ('Datsun', '160J'),
    ('Datsun', '240Z'),
    ('Datsun', '260Z'),
    ('Datsun', '280ZX'),
    ('Denza', 'D9'),
    ('Denza', 'Z9GT'),
    ('DFM', 'Forthing 3'),
    ('DFM', 'Forthing 4'),
    ('DFM', 'Forthing 5'),
    ('DFM', 'Forthing 7'),
    ('DFM', 'Forthing 9'),
    ('DFM', 'Rich 6'),
    ('DFM', 'Rich 9'),
    ('DFSK', 'Fengon 5'),
    ('DFSK', 'Fengon 500'),
    ('DFSK', 'Fengon 580'),
    ('DFSK', 'Fengon 600'),
    ('DFSK', 'Fengon 7'),
    ('DFSK', 'Fengon E5'),
    ('DKW', 'F 102'),
    ('DKW', 'F 11/F 12'),
    ('DKW', 'Junior'),
    ('DKW', 'Meisterklasse'),
    ('DKW', 'Monza'),
    ('DKW', 'Munga'),
    ('DKW', 'Sonderklasse'),
    ('DKW', '3=6'),
    ('Dodge', 'Avenger'),
    ('Dodge', 'Caliber'),
    ('Dodge', 'Journey'),
    ('Dodge', 'Nitro'),
    ('Dodge', 'Viper'),
    ('Dongfeng', 'Box'),
    ('Dongfeng', 'Huge'),
    ('DS Automobiles', 'DS 3'),
    ('DS Automobiles', 'DS 4'),
    ('DS Automobiles', 'DS 5'),
    ('DS Automobiles', 'DS 7'),
    ('DS Automobiles', 'DS 9'),
    ('DS Automobiles', 'NÂ°4'),
    ('DS Automobiles', 'NÂ°8'),
    ('e.GO Mobile', 'e.wave X'),
    ('e.GO Mobile', 'Life'),
    ('Elaris', 'Beo'),
    ('Elaris', 'Caro'),
    ('Elaris', 'Caro S'),
    ('Elaris', 'Dyo'),
    ('Elaris', 'Finn'),
    ('Elaris', 'Jaco'),
    ('Elaris', 'Lenn'),
    ('Elaris', 'Leo'),
    ('Elaris', 'Pio'),
    ('Ferrari', 'Amalfi'),
    ('Ferrari', 'California'),
    ('Ferrari', 'California T'),
    ('Ferrari', 'Daytona SP3'),
    ('Ferrari', 'Dino 206 GT'),
    ('Ferrari', 'Dino 246 GT/GTS'),
    ('Ferrari', 'Dino 308 GT 4'),
    ('Ferrari', 'Enzo Ferrari'),
    ('Ferrari', 'F12 berlinetta'),
    ('Ferrari', 'F12 tdf'),
    ('Ferrari', 'F355'),
    ('Ferrari', 'F40'),
    ('Ferrari', 'F430'),
    ('Ferrari', 'F50'),
    ('Ferrari', 'F8'),
    ('Ferrari', 'F80'),
    ('Ferrari', 'FF'),
    ('Ferrari', 'GTC4Lusso'),
    ('Ferrari', 'LaFerrari'),
    ('Ferrari', 'Mondial'),
    ('Ferrari', 'Portofino'),
    ('Ferrari', 'Portofino M'),
    ('Ferrari', 'Purosangue'),
    ('Ferrari', 'Roma'),
    ('Ferrari', 'SF90'),
    ('Ferrari', 'Testarossa'),
    ('Ferrari', '12Cilindri'),
    ('Ferrari', '166 Inter Touring'),
    ('Ferrari', '195 Inter Ghia'),
    ('Ferrari', '212 Pinin Farina'),
    ('Ferrari', '212 Vignale'),
    ('Ferrari', '250 Europa'),
    ('Ferrari', '250 Europa GT'),
    ('Ferrari', '250 GT 2+2'),
    ('Ferrari', '250 GT Berlinetta Lusso'),
    ('Ferrari', '250 GT Berlinetta LWB'),
    ('Ferrari', '250 GT Berlinetta SWB'),
    ('Ferrari', '250 GT Boano/Ellena'),
    ('Ferrari', '250 GT Cabriolet'),
    ('Ferrari', '250 GT CoupÃ©'),
    ('Ferrari', '250 GT Spyder California'),
    ('Ferrari', '250 GTO'),
    ('Ferrari', '275 GTB Long-Nose'),
    ('Ferrari', '275 GTB Short-Nose'),
    ('Ferrari', '275 GTB/4'),
    ('Ferrari', '275 GTS'),
    ('Ferrari', '288 GTO'),
    ('Ferrari', '296'),
    ('Ferrari', '308'),
    ('Ferrari', '328'),
    ('Ferrari', '330 GT 2+2'),
    ('Ferrari', '330 GTC/GTS'),
    ('Ferrari', '348'),
    ('Ferrari', '360'),
    ('Ferrari', '365 California Spyder'),
    ('Ferrari', '365 GT 2+2'),
    ('Ferrari', '365 GT/4 BB'),
    ('Ferrari', '365 GT4 2+2'),
    ('Ferrari', '365 GTB/GTS/4'),
    ('Ferrari', '365 GTC/4'),
    ('Ferrari', '365 GTC/GTS'),
    ('Ferrari', '400 GT'),
    ('Ferrari', '412 GT'),
    ('Ferrari', '456 GT'),
    ('Ferrari', '456M GT'),
    ('Ferrari', '458'),
    ('Ferrari', '488'),
    ('Ferrari', '500 Superfast'),
    ('Ferrari', '512 BB'),
    ('Ferrari', '512 M'),
    ('Ferrari', '512 TR'),
    ('Ferrari', '550 Maranello'),
    ('Ferrari', '575M Maranello'),
    ('Ferrari', '599 GTB Fiorano'),
    ('Ferrari', '612 Scaglietti'),
    ('Ferrari', '812'),
    ('Ferrari', '849 Testarossa'),
    ('Fiat', 'Argenta'),
    ('Fiat', 'Barchetta'),
    ('Fiat', 'Brava'),
    ('Fiat', 'Bravo'),
    ('Fiat', 'Cinquecento'),
    ('Fiat', 'CoupÃ©'),
    ('Fiat', 'Croma'),
    ('Fiat', 'Dino'),
    ('Fiat', 'DoblÃ²'),
    ('Fiat', 'Ducato'),
    ('Fiat', 'Fiorino'),
    ('Fiat', 'Freemont'),
    ('Fiat', 'Fullback'),
    ('Fiat', 'Grande Panda'),
    ('Fiat', 'Idea'),
    ('Fiat', 'Linea'),
    ('Fiat', 'Marea'),
    ('Fiat', 'Multipla'),
    ('Fiat', 'Palio'),
    ('Fiat', 'Panda'),
    ('Fiat', 'Pandina'),
    ('Fiat', 'Punto'),
    ('Fiat', 'Qubo'),
    ('Fiat', 'Regata'),
    ('Fiat', 'Ritmo'),
    ('Fiat', 'Scudo'),
    ('Fiat', 'Sedici'),
    ('Fiat', 'Seicento'),
    ('Fiat', 'Stilo'),
    ('Fiat', 'Strada'),
    ('Fiat', 'Talento'),
    ('Fiat', 'Tempra'),
    ('Fiat', 'Tipo'),
    ('Fiat', 'Topolino'),
    ('Fiat', 'Ulysse'),
    ('Fiat', 'Uno'),
    ('Fiat', 'X1/9'),
    ('Fiat', '124'),
    ('Fiat', '124 Spider'),
    ('Fiat', '125'),
    ('Fiat', '126'),
    ('Fiat', '127'),
    ('Fiat', '128'),
    ('Fiat', '130'),
    ('Fiat', '131'),
    ('Fiat', '132'),
    ('Fiat', '500'),
    ('Fiat', '500L'),
    ('Fiat', '500X'),
    ('Fiat', '600'),
    ('Fiat', '770 S'),
    ('Fiat', '850'),
    ('Fiat', '2300 CoupÃ©'),
    ('Firefly', 'Firefly'),
    ('Fisker', 'Karma'),
    ('Fisker', 'Ocean'),
    ('FMR', 'Kabinenroller'),
    ('FMR', 'Tg 500'),
    ('Ford', 'B-MAX'),
    ('Ford', 'Bronco'),
    ('Ford', 'C-MAX'),
    ('Ford', 'Capri'),
    ('Ford', 'Consul'),
    ('Ford', 'Cougar'),
    ('Ford', 'EcoSport'),
    ('Ford', 'Edge'),
    ('Ford', 'Escort'),
    ('Ford', 'Explorer'),
    ('Ford', 'Explorer EV'),
    ('Ford', 'Fiesta'),
    ('Ford', 'Fiesta Courier'),
    ('Ford', 'Focus'),
    ('Ford', 'Fusion'),
    ('Ford', 'Galaxy'),
    ('Ford', 'Granada'),
    ('Ford', 'GT'),
    ('Ford', 'Ka'),
    ('Ford', 'Kuga'),
    ('Ford', 'Maverick'),
    ('Ford', 'Mondeo'),
    ('Ford', 'Mustang'),
    ('Ford', 'Mustang Mach-E'),
    ('Ford', 'Nugget'),
    ('Ford', 'Orion'),
    ('Ford', 'Probe'),
    ('Ford', 'Puma'),
    ('Ford', 'Ranger'),
    ('Ford', 'RS200'),
    ('Ford', 'S-MAX'),
    ('Ford', 'Scorpio'),
    ('Ford', 'Sierra'),
    ('Ford', 'Streetka'),
    ('Ford', 'Taunus 12M/15M'),
    ('Ford', 'Taunus 17M/20M/26M'),
    ('Ford', 'Taunus TC'),
    ('Ford', 'Tourneo Connect'),
    ('Ford', 'Tourneo Courier'),
    ('Ford', 'Tourneo Custom'),
    ('Ford', 'Transit'),
    ('Ford', 'Transit Connect'),
    ('Ford', 'Transit Courier'),
    ('Ford', 'Transit Custom'),
    ('Ford', 'Windstar'),
    ('Foton', '3'),
    ('Foton', '4'),
    ('Genesis', 'G70'),
    ('Genesis', 'G80'),
    ('Genesis', 'G90'),
    ('Genesis', 'GV60'),
    ('Genesis', 'GV70'),
    ('Genesis', 'GV80'),
    ('Glas', 'Goggomobil'),
    ('Glas', 'Goggomobil/Isar'),
    ('Glas', 'GT'),
    ('Glas', '1004/1204/1304'),
    ('Glas', '1700'),
    ('Glas', '2600 V8'),
    ('Goliath', 'GP 1100'),
    ('Goliath', 'GP 700/900'),
    ('Gutbrod', 'Superior'),
    ('GWM', 'HAVAL H6'),
    ('GWM', 'HAVAL Jolion Pro'),
    ('GWM', 'ORA 03'),
    ('GWM', 'ORA 07'),
    ('GWM', 'WEY 03'),
    ('GWM', 'WEY 05'),
    ('Hansa', '1100'),
    ('Heinkel', 'Kabine'),
    ('HiPhi', 'X'),
    ('HiPhi', 'Z'),
    ('Honda', 'Accord'),
    ('Honda', 'Civic'),
    ('Honda', 'Concerto'),
    ('Honda', 'CR-V'),
    ('Honda', 'CR-Z'),
    ('Honda', 'CRX'),
    ('Honda', 'e'),
    ('Honda', 'e:Ny1'),
    ('Honda', 'FR-V'),
    ('Honda', 'HR-V'),
    ('Honda', 'Insight'),
    ('Honda', 'Integra'),
    ('Honda', 'Jazz'),
    ('Honda', 'Legend'),
    ('Honda', 'Logo'),
    ('Honda', 'NSX'),
    ('Honda', 'Prelude'),
    ('Honda', 'Quintet'),
    ('Honda', 'S2000'),
    ('Honda', 'Shuttle'),
    ('Honda', 'Stream'),
    ('Honda', 'ZR-V'),
    ('Hongqi', 'E-HS9'),
    ('Hongqi', 'EH7'),
    ('Hongqi', 'EHS7'),
    ('Hongqi', 'H9'),
    ('Hongqi', 'HS5'),
    ('Hummer', 'H2'),
    ('Hummer', 'H3'),
    ('Hyundai', 'Accent'),
    ('Hyundai', 'Atos'),
    ('Hyundai', 'Atos Prime'),
    ('Hyundai', 'Bayon'),
    ('Hyundai', 'CoupÃ©'),
    ('Hyundai', 'Elantra'),
    ('Hyundai', 'Genesis'),
    ('Hyundai', 'Getz'),
    ('Hyundai', 'Grand Santa Fe'),
    ('Hyundai', 'Grandeur'),
    ('Hyundai', 'H 100'),
    ('Hyundai', 'H-1'),
    ('Hyundai', 'H350'),
    ('Hyundai', 'i10'),
    ('Hyundai', 'i20'),
    ('Hyundai', 'i30'),
    ('Hyundai', 'i40'),
    ('Hyundai', 'Inster'),
    ('Hyundai', 'IONIQ'),
    ('Hyundai', 'IONIQ 3'),
    ('Hyundai', 'IONIQ 5'),
    ('Hyundai', 'IONIQ 6'),
    ('Hyundai', 'IONIQ 9'),
    ('Hyundai', 'ix20'),
    ('Hyundai', 'ix35'),
    ('Hyundai', 'ix55'),
    ('Hyundai', 'Kona'),
    ('Hyundai', 'Lantra'),
    ('Hyundai', 'Matrix'),
    ('Hyundai', 'Nexo'),
    ('Hyundai', 'Pony'),
    ('Hyundai', 'Santa Fe'),
    ('Hyundai', 'Sonata'),
    ('Hyundai', 'Staria'),
    ('Hyundai', 'Terracan'),
    ('Hyundai', 'Trajet'),
    ('Hyundai', 'Tucson'),
    ('Hyundai', 'Veloster'),
    ('Hyundai', 'XG'),
    ('Hyundai Precision', 'Galloper'),
    ('Hyundai Precision', 'Galloper Wagon'),
    ('Hyundai Precision', 'Santamo'),
    ('IFA', 'F 8'),
    ('IFA', 'F 9'),
    ('Ineos', 'Grenadier'),
    ('Infiniti', 'EX'),
    ('Infiniti', 'FX'),
    ('Infiniti', 'G'),
    ('Infiniti', 'M'),
    ('Infiniti', 'Q30'),
    ('Infiniti', 'Q50'),
    ('Infiniti', 'Q60'),
    ('Infiniti', 'Q70'),
    ('Infiniti', 'QX30'),
    ('Infiniti', 'QX50'),
    ('Infiniti', 'QX70'),
    ('Isuzu', 'D-Max'),
    ('Isuzu', 'Midi'),
    ('Isuzu', 'Trooper'),
    ('JAC Motors', 'E30X'),
    ('JAC Motors', 'JS8 Pro'),
    ('JAC Motors', 'T9'),
    ('JAC Motors', '8 Pro'),
    ('Jaecoo', '7'),
    ('Jaguar', 'Daimler'),
    ('Jaguar', 'E-Pace'),
    ('Jaguar', 'E-Type'),
    ('Jaguar', 'F-Pace'),
    ('Jaguar', 'F-Type'),
    ('Jaguar', 'I-Pace'),
    ('Jaguar', 'S-Type'),
    ('Jaguar', 'X-Type'),
    ('Jaguar', 'XE'),
    ('Jaguar', 'XF'),
    ('Jaguar', 'XJ'),
    ('Jaguar', 'XJS'),
    ('Jaguar', 'XK'),
    ('Jeep', 'Avenger'),
    ('Jeep', 'Cherokee'),
    ('Jeep', 'Commander'),
    ('Jeep', 'Compass'),
    ('Jeep', 'Gladiator'),
    ('Jeep', 'Grand Cherokee'),
    ('Jeep', 'Patriot'),
    ('Jeep', 'Renegade'),
    ('Jeep', 'Wrangler'),
    ('KGM', 'Actyon'),
    ('KGM', 'Korando'),
    ('KGM', 'Musso'),
    ('KGM', 'Musso EV'),
    ('KGM', 'Rexton'),
    ('KGM', 'Tivoli'),
    ('KGM', 'Torres'),
    ('KGM', 'Torres EVX'),
    ('Kia', 'Besta'),
    ('Kia', 'Carens'),
    ('Kia', 'Carnival'),
    ('Kia', 'Ceed'),
    ('Kia', 'Cerato'),
    ('Kia', 'Clarus'),
    ('Kia', 'EV2'),
    ('Kia', 'EV3'),
    ('Kia', 'EV4'),
    ('Kia', 'EV5'),
    ('Kia', 'EV6'),
    ('Kia', 'EV9'),
    ('Kia', 'Joice'),
    ('Kia', 'K4'),
    ('Kia', 'Magentis'),
    ('Kia', 'Niro'),
    ('Kia', 'Opirus'),
    ('Kia', 'Optima'),
    ('Kia', 'Picanto'),
    ('Kia', 'Pregio'),
    ('Kia', 'Pride'),
    ('Kia', 'PV5'),
    ('Kia', 'Retona'),
    ('Kia', 'Rio'),
    ('Kia', 'Roadster'),
    ('Kia', 'Seltos'),
    ('Kia', 'Sephia'),
    ('Kia', 'Shuma'),
    ('Kia', 'Sorento'),
    ('Kia', 'Soul'),
    ('Kia', 'Sportage'),
    ('Kia', 'Stinger'),
    ('Kia', 'Stonic'),
    ('Kia', 'Venga'),
    ('Kia', 'XCeed'),
    ('Koenigsegg', 'Agera'),
    ('Koenigsegg', 'CC'),
    ('Koenigsegg', 'CC850'),
    ('Koenigsegg', 'CC8S'),
    ('Koenigsegg', 'CCR'),
    ('Koenigsegg', 'Gemera'),
    ('Koenigsegg', 'Jesko'),
    ('Koenigsegg', 'One:1'),
    ('Koenigsegg', 'Regera'),
    ('Lada', 'Granta'),
    ('Lada', 'Kalina'),
    ('Lada', 'Niva/Taiga/4x4'),
    ('Lada', 'Priora'),
    ('Lada', 'Samara'),
    ('Lada', 'Urban'),
    ('Lada', 'Vesta'),
    ('Lada', '110/111/112'),
    ('Lamborghini', 'Aventador'),
    ('Lamborghini', 'Centenario'),
    ('Lamborghini', 'Countach'),
    ('Lamborghini', 'Diablo'),
    ('Lamborghini', 'Espada'),
    ('Lamborghini', 'Gallardo'),
    ('Lamborghini', 'HuracÃ¡n'),
    ('Lamborghini', 'Islero'),
    ('Lamborghini', 'Jalpa'),
    ('Lamborghini', 'Jarama'),
    ('Lamborghini', 'LM002'),
    ('Lamborghini', 'Miura'),
    ('Lamborghini', 'MurciÃ©lago'),
    ('Lamborghini', 'ReventÃ³n'),
    ('Lamborghini', 'Revuelto'),
    ('Lamborghini', 'Silhouette'),
    ('Lamborghini', 'Temerario'),
    ('Lamborghini', 'Urraco'),
    ('Lamborghini', 'Urus'),
    ('Lamborghini', 'Veneno'),
    ('Lamborghini', '350 GT'),
    ('Lamborghini', '400 GT'),
    ('Lancia', 'Beta'),
    ('Lancia', 'CoupÃ©'),
    ('Lancia', 'Dedra'),
    ('Lancia', 'Delta'),
    ('Lancia', 'Flavia'),
    ('Lancia', 'Fulvia'),
    ('Lancia', 'Gamma'),
    ('Lancia', 'H.P.Executive'),
    ('Lancia', 'Kappa'),
    ('Lancia', 'Lybra'),
    ('Lancia', 'Musa'),
    ('Lancia', 'Phedra'),
    ('Lancia', 'Prisma'),
    ('Lancia', 'Stratos HF'),
    ('Lancia', 'Thema'),
    ('Lancia', 'Thesis'),
    ('Lancia', 'Trevi'),
    ('Lancia', 'Voyager'),
    ('Lancia', 'Y'),
    ('Lancia', 'Y10'),
    ('Lancia', 'Ypsilon'),
    ('Lancia', 'Zeta'),
    ('Lancia', '2000'),
    ('Land Rover', 'Defender'),
    ('Land Rover', 'Discovery'),
    ('Land Rover', 'Discovery Sport'),
    ('Land Rover', 'Freelander'),
    ('Land Rover', 'Range Rover'),
    ('Land Rover', 'Range Rover Evoque'),
    ('Land Rover', 'Range Rover Sport'),
    ('Land Rover', 'Range Rover Velar'),
    ('Leapmotor', 'B10'),
    ('Leapmotor', 'C10'),
    ('Leapmotor', 'T03'),
    ('Lexus', 'CT'),
    ('Lexus', 'ES'),
    ('Lexus', 'GS'),
    ('Lexus', 'IS'),
    ('Lexus', 'LBX'),
    ('Lexus', 'LC'),
    ('Lexus', 'LM'),
    ('Lexus', 'LS'),
    ('Lexus', 'NX'),
    ('Lexus', 'RC'),
    ('Lexus', 'RX'),
    ('Lexus', 'RZ'),
    ('Lexus', 'SC'),
    ('Lexus', 'UX'),
    ('Ligier', 'JS 50'),
    ('Ligier', 'JS 60'),
    ('Ligier', 'Myli'),
    ('Linzda', 'M3'),
    ('Lloyd', 'Alexander Frua'),
    ('Lloyd', 'Arabella'),
    ('Lloyd', '250'),
    ('Lloyd', '300'),
    ('Lloyd', '400'),
    ('Lloyd', '600/Alexander'),
    ('Lotus', 'Eletre'),
    ('Lotus', 'Elise'),
    ('Lotus', 'Emeya'),
    ('Lotus', 'Emira'),
    ('Lotus', 'Esprit'),
    ('Lotus', 'Europa S'),
    ('Lotus', 'Evija'),
    ('Lotus', 'Evora'),
    ('Lotus', 'Exige'),
    ('Lotus', '2-Eleven'),
    ('Lotus', '3-Eleven'),
    ('Lucid', 'Air'),
    ('Lucid', 'Gravity'),
    ('Lynk & Co', '1'),
    ('Lynk & Co', '2'),
    ('Lynk & Co', '8'),
    ('Maserati', 'Biturbo'),
    ('Maserati', 'Bora'),
    ('Maserati', 'CoupÃ©'),
    ('Maserati', 'Ghibli'),
    ('Maserati', 'GranCabrio'),
    ('Maserati', 'GranSport'),
    ('Maserati', 'GranTurismo'),
    ('Maserati', 'Grecale'),
    ('Maserati', 'GT2 Stradale'),
    ('Maserati', 'Indy'),
    ('Maserati', 'Karif'),
    ('Maserati', 'Khamsin'),
    ('Maserati', 'Kyalami'),
    ('Maserati', 'Levante'),
    ('Maserati', 'MC12'),
    ('Maserati', 'MC20'),
    ('Maserati', 'MCPURA'),
    ('Maserati', 'Merak'),
    ('Maserati', 'Mexico'),
    ('Maserati', 'Mistral'),
    ('Maserati', 'Quattroporte'),
    ('Maserati', 'Shamal'),
    ('Maserati', 'Spyder'),
    ('Maserati', '228'),
    ('Maserati', '3200 GT'),
    ('Maserati', '3500 GT'),
    ('Maxus', 'Deliver 3'),
    ('Maxus', 'Deliver 5'),
    ('Maxus', 'Deliver 7'),
    ('Maxus', 'Deliver 9'),
    ('Maxus', 'eTERRON 9'),
    ('Maxus', 'Euniq 5'),
    ('Maxus', 'Euniq 6'),
    ('Maxus', 'EV80'),
    ('Maxus', 'Mifa 9'),
    ('Maxus', 'T60 MAX'),
    ('Maxus', 'T90 EV'),
    ('Maybach', 'Maybach'),
    ('Mazda', 'B-Serie'),
    ('Mazda', 'BT-50'),
    ('Mazda', 'CX-3'),
    ('Mazda', 'CX-30'),
    ('Mazda', 'CX-5'),
    ('Mazda', 'CX-60'),
    ('Mazda', 'CX-6e'),
    ('Mazda', 'CX-7'),
    ('Mazda', 'CX-80'),
    ('Mazda', 'Demio'),
    ('Mazda', 'E-Serie'),
    ('Mazda', 'MPV'),
    ('Mazda', 'MX-3'),
    ('Mazda', 'MX-30'),
    ('Mazda', 'MX-5'),
    ('Mazda', 'Premacy'),
    ('Mazda', 'RX-7'),
    ('Mazda', 'RX-8'),
    ('Mazda', 'Tribute'),
    ('Mazda', 'Xedos 6'),
    ('Mazda', 'Xedos 9'),
    ('Mazda', '2'),
    ('Mazda', '2 Hybrid'),
    ('Mazda', '3'),
    ('Mazda', '5'),
    ('Mazda', '6'),
    ('Mazda', '121'),
    ('Mazda', '323'),
    ('Mazda', '626'),
    ('Mazda', '929'),
    ('McLaren', 'GT Series'),
    ('McLaren', 'Sports Series'),
    ('McLaren', 'Super Series'),
    ('McLaren', 'Supercar Series'),
    ('McLaren', 'Ultimate Series'),
    ('Melkus', 'RS 1000'),
    ('Mercedes-Benz', 'A-Klasse'),
    ('Mercedes-Benz', 'AMG GT'),
    ('Mercedes-Benz', 'AMG GT 4-TÃ¼rer CoupÃ©'),
    ('Mercedes-Benz', 'AMG ONE'),
    ('Mercedes-Benz', 'AMG PureSpeed'),
    ('Mercedes-Benz', 'B-Klasse'),
    ('Mercedes-Benz', 'C-Klasse'),
    ('Mercedes-Benz', 'Citan'),
    ('Mercedes-Benz', 'CL-Klasse'),
    ('Mercedes-Benz', 'CLA'),
    ('Mercedes-Benz', 'CLC-Klasse'),
    ('Mercedes-Benz', 'CLE'),
    ('Mercedes-Benz', 'CLK GTR'),
    ('Mercedes-Benz', 'CLK-Klasse'),
    ('Mercedes-Benz', 'CLS'),
    ('Mercedes-Benz', 'E-Klasse'),
    ('Mercedes-Benz', 'EQA'),
    ('Mercedes-Benz', 'EQB'),
    ('Mercedes-Benz', 'EQC'),
    ('Mercedes-Benz', 'EQE'),
    ('Mercedes-Benz', 'EQE SUV'),
    ('Mercedes-Benz', 'EQS'),
    ('Mercedes-Benz', 'EQS SUV'),
    ('Mercedes-Benz', 'EQT'),
    ('Mercedes-Benz', 'EQV'),
    ('Mercedes-Benz', 'G-Klasse'),
    ('Mercedes-Benz', 'GL-Klasse'),
    ('Mercedes-Benz', 'GLA'),
    ('Mercedes-Benz', 'GLB'),
    ('Mercedes-Benz', 'GLC'),
    ('Mercedes-Benz', 'GLE'),
    ('Mercedes-Benz', 'GLK-Klasse'),
    ('Mercedes-Benz', 'GLS'),
    ('Mercedes-Benz', 'M-Klasse'),
    ('Mercedes-Benz', 'R-Klasse'),
    ('Mercedes-Benz', 'S-Klasse'),
    ('Mercedes-Benz', 'SL-Klasse'),
    ('Mercedes-Benz', 'SLC'),
    ('Mercedes-Benz', 'SLK-Klasse'),
    ('Mercedes-Benz', 'SLR McLaren'),
    ('Mercedes-Benz', 'SLS AMG'),
    ('Mercedes-Benz', 'Sprinter'),
    ('Mercedes-Benz', 'T-Klasse'),
    ('Mercedes-Benz', 'V-Klasse'),
    ('Mercedes-Benz', 'Vaneo'),
    ('Mercedes-Benz', 'Viano'),
    ('Mercedes-Benz', 'Vito'),
    ('Mercedes-Benz', 'VLE'),
    ('Mercedes-Benz', 'W 105/128/180'),
    ('Mercedes-Benz', 'W 108/109'),
    ('Mercedes-Benz', 'W 110'),
    ('Mercedes-Benz', 'W 111/112'),
    ('Mercedes-Benz', 'W 114/115'),
    ('Mercedes-Benz', 'W 120/121'),
    ('Mercedes-Benz', 'W 136/191'),
    ('Mercedes-Benz', 'W 186/189'),
    ('Mercedes-Benz', 'W 187'),
    ('Mercedes-Benz', 'W 188'),
    ('Mercedes-Benz', 'X-Klasse'),
    ('Mercedes-Benz', '123'),
    ('Mercedes-Benz', '124'),
    ('Mercedes-Benz', '190'),
    ('Mercedes-Benz', '600'),
    ('Messerschmitt', 'Kabinenroller'),
    ('MG', 'Cyberster'),
    ('MG', 'F'),
    ('MG', 'HS/EHS'),
    ('MG', 'Marvel R'),
    ('MG', 'MG3'),
    ('MG', 'MG4'),
    ('MG', 'MG4 Urban'),
    ('MG', 'MG5'),
    ('MG', 'MGS5'),
    ('MG', 'MGS6'),
    ('MG', 'MGS9'),
    ('MG', 'TF'),
    ('MG', 'XPower SV'),
    ('MG', 'ZR'),
    ('MG', 'ZS'),
    ('MG', 'ZT'),
    ('Micro', 'Microlino'),
    ('Microcar', 'DuÃ©'),
    ('Microcar', 'M.Go'),
    ('MINI', 'Aceman'),
    ('MINI', 'Clubman'),
    ('MINI', 'Countryman'),
    ('MINI', 'MINI'),
    ('MINI', 'Paceman'),
    ('Mitsubishi', 'ASX'),
    ('Mitsubishi', 'Carisma'),
    ('Mitsubishi', 'Carisma GT Evo'),
    ('Mitsubishi', 'Colt'),
    ('Mitsubishi', 'Cordia'),
    ('Mitsubishi', 'Eclipse'),
    ('Mitsubishi', 'Eclipse Cross'),
    ('Mitsubishi', 'Galant'),
    ('Mitsubishi', 'Grandis'),
    ('Mitsubishi', 'i-MiEV'),
    ('Mitsubishi', 'L200'),
    ('Mitsubishi', 'L300'),
    ('Mitsubishi', 'L400'),
    ('Mitsubishi', 'Lancer'),
    ('Mitsubishi', 'Lancer Evo'),
    ('Mitsubishi', 'Outlander'),
    ('Mitsubishi', 'Pajero'),
    ('Mitsubishi', 'Pajero Classic'),
    ('Mitsubishi', 'Pajero Pinin'),
    ('Mitsubishi', 'Pajero Sport'),
    ('Mitsubishi', 'Sapporo'),
    ('Mitsubishi', 'Sigma'),
    ('Mitsubishi', 'Space Gear'),
    ('Mitsubishi', 'Space Runner'),
    ('Mitsubishi', 'Space Star'),
    ('Mitsubishi', 'Space Wagon'),
    ('Mitsubishi', 'Starion'),
    ('Mitsubishi', 'Tredia'),
    ('Mitsubishi', '3000 GT'),
    ('Mobilize', 'Bento'),
    ('Mobilize', 'Duo'),
    ('Morgan', 'Aero'),
    ('Morgan', 'Aero Supersports'),
    ('Morgan', 'Plus 4'),
    ('Morgan', 'Plus 8'),
    ('Morgan', 'Plus Four'),
    ('Morgan', 'Plus Six'),
    ('Morgan', 'Roadster'),
    ('Morgan', 'Supersport'),
    ('Morgan', '46116'),
    ('NIO', 'EL6'),
    ('NIO', 'EL7'),
    ('NIO', 'EL8'),
    ('NIO', 'ET5'),
    ('NIO', 'ET7'),
    ('Nissan', 'Almera'),
    ('Nissan', 'Almera Tino'),
    ('Nissan', 'Ariya'),
    ('Nissan', 'Bluebird'),
    ('Nissan', 'Cherry'),
    ('Nissan', 'Cube'),
    ('Nissan', 'GT-R'),
    ('Nissan', 'Interstar'),
    ('Nissan', 'Juke'),
    ('Nissan', 'Kubistar'),
    ('Nissan', 'Leaf'),
    ('Nissan', 'Maxima'),
    ('Nissan', 'Micra'),
    ('Nissan', 'Murano'),
    ('Nissan', 'Navara'),
    ('Nissan', 'Note'),
    ('Nissan', 'NP300'),
    ('Nissan', 'NV200'),
    ('Nissan', 'NV250'),
    ('Nissan', 'NV300'),
    ('Nissan', 'NV400'),
    ('Nissan', 'Pathfinder'),
    ('Nissan', 'Patrol'),
    ('Nissan', 'Pickup'),
    ('Nissan', 'Pixo'),
    ('Nissan', 'Prairie'),
    ('Nissan', 'Primastar'),
    ('Nissan', 'Primera'),
    ('Nissan', 'Pulsar'),
    ('Nissan', 'Qashqai'),
    ('Nissan', 'Serena'),
    ('Nissan', 'Sunny'),
    ('Nissan', 'Terrano'),
    ('Nissan', 'Tiida'),
    ('Nissan', 'Townstar'),
    ('Nissan', 'Vanette'),
    ('Nissan', 'X-Trail'),
    ('Nissan', '100NX'),
    ('Nissan', '200SX'),
    ('Nissan', '300ZX'),
    ('Nissan', '350Z'),
    ('Nissan', '370Z'),
    ('NSU', 'Prinz'),
    ('NSU', 'Prinz 1000'),
    ('NSU', 'Ro 80'),
    ('NSU', 'Sport-Prinz'),
    ('NSU', 'Typ 110 / 1200'),
    ('NSU', 'Wankel-Spider'),
    ('NSU-Fiat', 'Jagst'),
    ('NSU-Fiat', 'Weinsberg 500'),
    ('NSU-Fiat', '500 C'),
    ('NSU-Fiat', '1100/Neckar/Europa'),
    ('Omoda', '5'),
    ('Opel', 'ADAM'),
    ('Opel', 'Admiral'),
    ('Opel', 'Agila'),
    ('Opel', 'Ampera'),
    ('Opel', 'Antara'),
    ('Opel', 'Arena'),
    ('Opel', 'Ascona'),
    ('Opel', 'Astra'),
    ('Opel', 'Calibra'),
    ('Opel', 'Campo'),
    ('Opel', 'Cascada'),
    ('Opel', 'Chevette'),
    ('Opel', 'Combo'),
    ('Opel', 'Commodore'),
    ('Opel', 'Corsa'),
    ('Opel', 'Crossland'),
    ('Opel', 'Diplomat'),
    ('Opel', 'Frontera'),
    ('Opel', 'Grandland'),
    ('Opel', 'GT'),
    ('Opel', 'Insignia'),
    ('Opel', 'Kadett'),
    ('Opel', 'KapitÃ¤n'),
    ('Opel', 'KARL'),
    ('Opel', 'Manta'),
    ('Opel', 'Meriva'),
    ('Opel', 'Mokka'),
    ('Opel', 'Monterey'),
    ('Opel', 'Monza'),
    ('Opel', 'Movano'),
    ('Opel', 'Olympia'),
    ('Opel', 'Olympia A'),
    ('Opel', 'Omega'),
    ('Opel', 'Rekord'),
    ('Opel', 'Rocks Electric'),
    ('Opel', 'Senator'),
    ('Opel', 'Signum'),
    ('Opel', 'Sintra'),
    ('Opel', 'Speedster'),
    ('Opel', 'Tigra'),
    ('Opel', 'Vectra'),
    ('Opel', 'Vivaro'),
    ('Opel', 'Zafira'),
    ('Opel', 'Zafira Life'),
    ('ORA', 'Funky Cat'),
    ('Peugeot', 'Bipper'),
    ('Peugeot', 'Boxer'),
    ('Peugeot', 'Expert'),
    ('Peugeot', 'iOn'),
    ('Peugeot', 'Partner'),
    ('Peugeot', 'RCZ'),
    ('Peugeot', 'Rifter'),
    ('Peugeot', 'Traveller'),
    ('Peugeot', '104'),
    ('Peugeot', '106'),
    ('Peugeot', '107'),
    ('Peugeot', '108'),
    ('Peugeot', '204'),
    ('Peugeot', '205'),
    ('Peugeot', '206'),
    ('Peugeot', '207'),
    ('Peugeot', '208'),
    ('Peugeot', '304'),
    ('Peugeot', '305'),
    ('Peugeot', '306'),
    ('Peugeot', '307'),
    ('Peugeot', '308'),
    ('Peugeot', '309'),
    ('Peugeot', '405'),
    ('Peugeot', '406'),
    ('Peugeot', '407'),
    ('Peugeot', '408'),
    ('Peugeot', '504'),
    ('Peugeot', '505'),
    ('Peugeot', '508'),
    ('Peugeot', '604'),
    ('Peugeot', '605'),
    ('Peugeot', '607'),
    ('Peugeot', '806'),
    ('Peugeot', '807'),
    ('Peugeot', '1007'),
    ('Peugeot', '2008'),
    ('Peugeot', '3008'),
    ('Peugeot', '4007'),
    ('Peugeot', '4008'),
    ('Peugeot', '5008'),
    ('Polestar', '1'),
    ('Polestar', '2'),
    ('Polestar', '3'),
    ('Polestar', '4'),
    ('Polestar', '5'),
    ('Porsche', 'Boxster'),
    ('Porsche', 'Carrera GT'),
    ('Porsche', 'Cayenne'),
    ('Porsche', 'Cayman'),
    ('Porsche', 'Macan'),
    ('Porsche', 'Panamera'),
    ('Porsche', 'Taycan'),
    ('Porsche', '356'),
    ('Porsche', '550 Spyder'),
    ('Porsche', '911'),
    ('Porsche', '912'),
    ('Porsche', '914'),
    ('Porsche', '918 Spyder'),
    ('Porsche', '924'),
    ('Porsche', '928'),
    ('Porsche', '944'),
    ('Porsche', '959'),
    ('Porsche', '968'),
    ('Proton', '300'),
    ('Proton', '400'),
    ('Renault', 'Alaskan'),
    ('Renault', 'Arkana'),
    ('Renault', 'Austral'),
    ('Renault', 'Avantime'),
    ('Renault', 'Captur'),
    ('Renault', 'Caravelle'),
    ('Renault', 'Clio'),
    ('Renault', 'Dauphine'),
    ('Renault', 'Espace'),
    ('Renault', 'Express'),
    ('Renault', 'Fluence'),
    ('Renault', 'FrÃ©gate'),
    ('Renault', 'Fuego'),
    ('Renault', 'Kadjar'),
    ('Renault', 'Kangoo'),
    ('Renault', 'Koleos'),
    ('Renault', 'Laguna'),
    ('Renault', 'Latitude'),
    ('Renault', 'Master'),
    ('Renault', 'MÃ©gane'),
    ('Renault', 'Modus'),
    ('Renault', 'R11'),
    ('Renault', 'R12'),
    ('Renault', 'R14'),
    ('Renault', 'R15'),
    ('Renault', 'R17'),
    ('Renault', 'R18'),
    ('Renault', 'R19'),
    ('Renault', 'R20'),
    ('Renault', 'R21'),
    ('Renault', 'R25'),
    ('Renault', 'R30'),
    ('Renault', 'R4'),
    ('Renault', 'R5'),
    ('Renault', 'R6'),
    ('Renault', 'R9'),
    ('Renault', 'Rafale'),
    ('Renault', 'Rapid'),
    ('Renault', 'Safrane'),
    ('Renault', 'ScÃ©nic'),
    ('Renault', 'Sport Spider'),
    ('Renault', 'Symbioz'),
    ('Renault', 'Talisman'),
    ('Renault', 'Trafic'),
    ('Renault', 'Twingo'),
    ('Renault', 'Twizy'),
    ('Renault', 'Vel Satis'),
    ('Renault', 'Wind'),
    ('Renault', 'Zoe'),
    ('Renault', '4CV'),
    ('Rolls-Royce', 'Camargue'),
    ('Rolls-Royce', 'Corniche'),
    ('Rolls-Royce', 'Cullinan'),
    ('Rolls-Royce', 'Dawn'),
    ('Rolls-Royce', 'Ghost'),
    ('Rolls-Royce', 'Phantom'),
    ('Rolls-Royce', 'Silver Dawn'),
    ('Rolls-Royce', 'Silver Seraph'),
    ('Rolls-Royce', 'Silver Spur'),
    ('Rolls-Royce', 'Spectre'),
    ('Rolls-Royce', 'Wraith'),
    ('Rover', 'CityRover'),
    ('Rover', 'Streetwise'),
    ('Rover', '(Austin) Maestro'),
    ('Rover', '(Austin) Metro'),
    ('Rover', '(Austin) Montego'),
    ('Rover', '(Austin) SD'),
    ('Rover', '25'),
    ('Rover', '45'),
    ('Rover', '75'),
    ('Rover', '100'),
    ('Rover', '200'),
    ('Rover', '400'),
    ('Rover', '600'),
    ('Rover', '800'),
    ('Saab', '46268'),
    ('Saab', '9-4X'),
    ('Saab', '46270'),
    ('Saab', '90'),
    ('Saab', '99'),
    ('Saab', '900'),
    ('Saab', '900'),
    ('Saab', '9000'),
    ('Saab', '9000'),
    ('Sachsenring AW', 'P 240'),
    ('Sachsenring AW', 'P 70'),
    ('Sachsenring AW', 'Trabant'),
    ('SEAT', 'Alhambra'),
    ('SEAT', 'Altea'),
    ('SEAT', 'Arona'),
    ('SEAT', 'Arosa'),
    ('SEAT', 'Ateca'),
    ('SEAT', 'Cordoba'),
    ('SEAT', 'Exeo'),
    ('SEAT', 'Fura'),
    ('SEAT', 'Ibiza'),
    ('SEAT', 'Inca'),
    ('SEAT', 'Leon'),
    ('SEAT', 'Malaga'),
    ('SEAT', 'Marbella'),
    ('SEAT', 'Mii'),
    ('SEAT', 'Ronda'),
    ('SEAT', 'Tarraco'),
    ('SEAT', 'Toledo'),
    ('SERES', '3'),
    ('SERES', '5'),
    ('Silence', 'S04 Nanocar'),
    ('Skoda', 'Citigo'),
    ('Skoda', 'Elroq'),
    ('Skoda', 'Enyaq'),
    ('Skoda', 'Fabia'),
    ('Skoda', 'Favorit'),
    ('Skoda', 'Felicia'),
    ('Skoda', 'Forman'),
    ('Skoda', 'Kamiq'),
    ('Skoda', 'Karoq'),
    ('Skoda', 'Kodiaq'),
    ('Skoda', 'Octavia'),
    ('Skoda', 'Praktik'),
    ('Skoda', 'Rapid'),
    ('Skoda', 'Roomster'),
    ('Skoda', 'S105/120/130/135'),
    ('Skoda', 'Scala'),
    ('Skoda', 'Superb'),
    ('Skoda', 'Yeti'),
    ('smart', 'forfour'),
    ('smart', 'fortwo'),
    ('smart', 'roadster'),
    ('smart', '#1'),
    ('smart', '#3'),
    ('smart', '#5'),
    ('Sono Motors', 'Sion'),
    ('SsangYong', 'Actyon'),
    ('SsangYong', 'Korando'),
    ('SsangYong', 'Kyron'),
    ('SsangYong', 'Musso'),
    ('SsangYong', 'Rexton'),
    ('SsangYong', 'Rodius'),
    ('SsangYong', 'Tivoli'),
    ('SsangYong', 'Torres'),
    ('SsangYong', 'XLV'),
    ('Subaru', 'BRZ'),
    ('Subaru', 'Crosstrek'),
    ('Subaru', 'Forester'),
    ('Subaru', 'Impreza'),
    ('Subaru', 'Justy'),
    ('Subaru', 'L-Serie'),
    ('Subaru', 'Legacy'),
    ('Subaru', 'Levorg'),
    ('Subaru', 'Libero'),
    ('Subaru', 'Outback'),
    ('Subaru', 'Solterra'),
    ('Subaru', 'SVX'),
    ('Subaru', 'Trezia'),
    ('Subaru', 'Tribeca'),
    ('Subaru', 'Uncharted'),
    ('Subaru', 'XT'),
    ('Subaru', 'XV'),
    ('Suzuki', 'Across'),
    ('Suzuki', 'Alto'),
    ('Suzuki', 'Baleno'),
    ('Suzuki', 'Cappuccino'),
    ('Suzuki', 'Carry'),
    ('Suzuki', 'Celerio'),
    ('Suzuki', 'Grand Vitara'),
    ('Suzuki', 'Ignis'),
    ('Suzuki', 'Jimny'),
    ('Suzuki', 'Kizashi'),
    ('Suzuki', 'Liana'),
    ('Suzuki', 'LJ'),
    ('Suzuki', 'S-Cross'),
    ('Suzuki', 'SJ'),
    ('Suzuki', 'Splash'),
    ('Suzuki', 'Swace'),
    ('Suzuki', 'Swift'),
    ('Suzuki', 'SX4'),
    ('Suzuki', 'Vitara'),
    ('Suzuki', 'Wagon R+'),
    ('SWM Motors', 'G01'),
    ('SWM Motors', 'G01A'),
    ('SWM Motors', 'G03'),
    ('SWM Motors', 'G05'),
    ('Talbot', 'Horizon'),
    ('Talbot', 'Matra Bagheera'),
    ('Talbot', 'Matra Murena'),
    ('Talbot', 'Matra Rancho'),
    ('Talbot', 'Samba'),
    ('Talbot', 'Simca 1510'),
    ('Talbot', 'Solara'),
    ('Talbot', 'Sunbeam'),
    ('Talbot', 'Tagora'),
    ('Tesla', 'Model 3'),
    ('Tesla', 'Model S'),
    ('Tesla', 'Model X'),
    ('Tesla', 'Model Y'),
    ('Tesla', 'Roadster'),
    ('Togg', 'T10F'),
    ('Togg', 'T10X'),
    ('Toyota', 'Auris'),
    ('Toyota', 'Avensis'),
    ('Toyota', 'Avensis Verso'),
    ('Toyota', 'Aygo'),
    ('Toyota', 'bZ4X'),
    ('Toyota', 'C-HR'),
    ('Toyota', 'C-HR+'),
    ('Toyota', 'Camry'),
    ('Toyota', 'Carina'),
    ('Toyota', 'Celica'),
    ('Toyota', 'Corolla'),
    ('Toyota', 'Corolla Cross'),
    ('Toyota', 'Corolla Verso'),
    ('Toyota', 'Cressida'),
    ('Toyota', 'GT86/GR86'),
    ('Toyota', 'Hiace'),
    ('Toyota', 'Highlander'),
    ('Toyota', 'Hilux'),
    ('Toyota', 'iQ'),
    ('Toyota', 'Land Cruiser J7/J9/J12/J15/J25'),
    ('Toyota', 'Land Cruiser J8/J10/J20'),
    ('Toyota', 'Mirai'),
    ('Toyota', 'MR2'),
    ('Toyota', 'Paseo'),
    ('Toyota', 'Picnic'),
    ('Toyota', 'Previa'),
    ('Toyota', 'Prius'),
    ('Toyota', 'Prius+'),
    ('Toyota', 'Proace'),
    ('Toyota', 'Proace City'),
    ('Toyota', 'Proace Max'),
    ('Toyota', 'RAV4'),
    ('Toyota', 'Starlet'),
    ('Toyota', 'Supra'),
    ('Toyota', 'Tercel'),
    ('Toyota', 'Urban Cruiser'),
    ('Toyota', 'Verso'),
    ('Toyota', 'Verso-S'),
    ('Toyota', 'Yaris'),
    ('Toyota', 'Yaris Cross'),
    ('Toyota', 'Yaris Verso'),
    ('Toyota', '4-Runner'),
    ('TYN-e', 'TX1-e'),
    ('VinFast', 'VF 6'),
    ('VinFast', 'VF 8'),
    ('VinFast', 'VF 9'),
    ('Volvo', 'C30'),
    ('Volvo', 'C40'),
    ('Volvo', 'C70'),
    ('Volvo', 'EC40'),
    ('Volvo', 'ES90'),
    ('Volvo', 'EX30'),
    ('Volvo', 'EX40'),
    ('Volvo', 'EX60'),
    ('Volvo', 'EX90'),
    ('Volvo', 'P1800'),
    ('Volvo', 'P1900'),
    ('Volvo', 'S40/V40/V50'),
    ('Volvo', 'S60/V60'),
    ('Volvo', 'S70/V70/XC70'),
    ('Volvo', 'S80'),
    ('Volvo', 'S90/V90'),
    ('Volvo', 'XC40'),
    ('Volvo', 'XC60'),
    ('Volvo', 'XC90'),
    ('Volvo', '66'),
    ('Volvo', '142/144/145'),
    ('Volvo', '164'),
    ('Volvo', '240'),
    ('Volvo', '242/244/245'),
    ('Volvo', '264/265/262'),
    ('Volvo', '264/265/262'),
    ('Volvo', '340/360'),
    ('Volvo', '343/345'),
    ('Volvo', '440/460/480'),
    ('Volvo', '740/760'),
    ('Volvo', '850'),
    ('Volvo', '940/960'),
    ('Voyah', 'Free'),
    ('VW', 'Arteon'),
    ('VW', 'Beetle'),
    ('VW', 'Bora'),
    ('VW', 'CC'),
    ('VW', 'Corrado'),
    ('VW', 'Derby'),
    ('VW', 'Eos'),
    ('VW', 'Fox'),
    ('VW', 'Golf'),
    ('VW', 'ID.3'),
    ('VW', 'ID.4'),
    ('VW', 'ID.5'),
    ('VW', 'ID.7'),
    ('VW', 'Iltis'),
    ('VW', 'Jetta'),
    ('VW', 'K 70'),
    ('VW', 'KÃ¤fer'),
    ('VW', 'Karmann Ghia'),
    ('VW', 'Lupo'),
    ('VW', 'Passat'),
    ('VW', 'Phaeton'),
    ('VW', 'Polo'),
    ('VW', 'Santana'),
    ('VW', 'Scirocco'),
    ('VW', 'Sharan'),
    ('VW', 'T-Cross'),
    ('VW', 'T-Roc'),
    ('VW', 'Taigo'),
    ('VW', 'Tayron'),
    ('VW', 'Tiguan'),
    ('VW', 'Touareg'),
    ('VW', 'Touran'),
    ('VW', 'up!'),
    ('VW', 'Vento'),
    ('VW', 'XL1'),
    ('VW', '181 Kurierwagen'),
    ('VW', '411'),
    ('VW', '412'),
    ('VW', '1500/1600'),
    ('VW Nutzfahrzeuge', 'Amarok'),
    ('VW Nutzfahrzeuge', 'Caddy'),
    ('VW Nutzfahrzeuge', 'Crafter'),
    ('VW Nutzfahrzeuge', 'Grand California'),
    ('VW Nutzfahrzeuge', 'ID. Buzz'),
    ('VW Nutzfahrzeuge', 'LT'),
    ('VW Nutzfahrzeuge', 'Taro'),
    ('VW Nutzfahrzeuge', 'Transporter'),
    ('Wartburg', '1.3'),
    ('Wartburg', '311'),
    ('Wartburg', '312'),
    ('Wartburg', '313'),
    ('Wartburg', '353'),
    ('WEY', 'Coffee 01'),
    ('Wiesmann', 'GT'),
    ('Wiesmann', 'Roadster'),
    ('XEV', 'YOYO'),
    ('XPeng', 'G6'),
    ('XPeng', 'G9'),
    ('XPeng', 'P7'),
    ('XPeng', 'P7+'),
    ('Yugo', 'Florida'),
    ('Yugo', '60/65'),
    ('ZEEKR', 'X'),
    ('ZEEKR', '1'),
    ('ZEEKR', '7GT'),
    ('ZEEKR', '7X'),
    ('ZÃ¼ndapp', 'Janus');

-- Optional quick checks:
-- SELECT COUNT(*) FROM european_car_make_models;
-- SELECT brand, COUNT(*) FROM european_car_make_models GROUP BY brand ORDER BY brand;
